-- BARMY360 - ESTATÍSTICAS DE ACESSOS E PAINEL ADM
-- Rode este arquivo no SQL Editor do Supabase da versão já instalada.

create table if not exists public.site_accesses (
  id bigint generated by default as identity primary key,
  page_path text not null,
  visitor_fingerprint text,
  referrer text,
  user_agent text,
  created_at timestamptz default now()
);
create index if not exists site_accesses_page_idx on public.site_accesses(page_path);
create index if not exists site_accesses_created_idx on public.site_accesses(created_at desc);
create index if not exists site_accesses_visitor_idx on public.site_accesses(visitor_fingerprint);

alter table public.site_accesses enable row level security;
drop policy if exists "site_accesses_no_public_read" on public.site_accesses;
create policy "site_accesses_no_public_read" on public.site_accesses for select using (false);
drop policy if exists "site_accesses_admin_read" on public.site_accesses;
create policy "site_accesses_admin_read" on public.site_accesses for select to authenticated using (true);

create or replace function public.registrar_acesso_site(pagina text, visitante text default null, referencia text default null)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  request_headers jsonb := coalesce(nullif(current_setting('request.headers', true), '')::jsonb, '{}'::jsonb);
  ua text := nullif(coalesce(request_headers->>'user-agent',''), '');
begin
  if nullif(trim(coalesce(pagina,'')), '') is null then return false; end if;
  insert into public.site_accesses(page_path, visitor_fingerprint, referrer, user_agent)
  values (left(trim(pagina),160), left(nullif(trim(coalesce(visitante,'')),''),160), left(nullif(trim(coalesce(referencia,'')),''),500), left(ua,500));
  return true;
end;
$$;
grant execute on function public.registrar_acesso_site(text,text,text) to anon, authenticated;
